export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const POST_REVIEW = 'POST_REVIEW';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const PRODUCT_ATTRIBUTES = 'PRODUCT_ATTRIBUTES'
